/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logica.MetodosBD;
import Logica.PdfDAO;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStream;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class ActividadesResueltas extends javax.swing.JFrame {

    PdfDAO p = null;
    MetodosBD metodosbd = new MetodosBD(this);

    int id = 0;

    /**
     * Creates new form ActividadesResueltas
     */
    public ActividadesResueltas() {
        initComponents();
        metodosbd.listarActividadesRealizadas();
        setLocationRelativeTo(null);

        jPanel_ListaTareas.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel_ListaTareas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ActividadesResueltas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 610));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 610));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        jPanel_ListaTareas.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_ListaTareas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de actividades resueltas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel_ListaTareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_ActividadesResueltas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_ActividadesResueltas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "Title 2", "Title 3"
            }
        ));
        jTable_ActividadesResueltas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ActividadesResueltasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_ActividadesResueltas);

        jPanel_ListaTareas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 370, 310));

        getContentPane().add(jPanel_ListaTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 107, 410, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OtraTarea - copia.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 588, 608));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_ActividadesResueltasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ActividadesResueltasMouseClicked

        int column = jTable_ActividadesResueltas.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / jTable_ActividadesResueltas.getRowHeight();

        if (row < jTable_ActividadesResueltas.getRowCount() && row >= 0 && column < jTable_ActividadesResueltas.getColumnCount() && column >= 0) {
            id = (int) jTable_ActividadesResueltas.getValueAt(row, 0);
            Object value = jTable_ActividadesResueltas.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getText().equals("Vacio")) {
                    JOptionPane.showMessageDialog(null, "No hay archivo");
                } else {
                    PdfDAO pd = new PdfDAO();
                    pd.ejecutar_archivoPDF(id);
                    try {
                        File directorio = new File("temp"); //Creas un nuevo directorio a nivel de tu jar.
                        directorio.mkdirs();
                        directorio.setWritable(true);
                        //copias la direccion
                        String archivo = directorio.getCanonicalPath() + File.pathSeparator + "Vertebrados - Yulieth Tusarma.pdf";
                        //nuevo archivo en esa direccion
                        File temp = new File(archivo);
                        InputStream is = this.getClass().getResourceAsStream("/archivosPDF/Vertebrados - Yulieth Tusarma.pdf");
                        FileOutputStream archivoDestino = new FileOutputStream(temp);
                        FileWriter fw = new FileWriter(temp);
                        byte[] buffer = new byte[512 * 1024];
                        //lees el archivo hasta que se acabe...
                        int nbLectura;
                        while ((nbLectura = is.read(buffer)) != -1) {
                            archivoDestino.write(buffer, 0, nbLectura);
                        }
                        //cierras el archivo,el inputS y el FileW
                        fw.close();
                        archivoDestino.close();
                        is.close();
                        //abres el archivo temporal
                        Desktop.getDesktop().open(temp);
                    } catch (Exception ex) {
                    }
                }

            } else {
                String name = "" + jTable_ActividadesResueltas.getValueAt(row, 1);

            }
        }

    }//GEN-LAST:event_jTable_ActividadesResueltasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActividadesResueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActividadesResueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActividadesResueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActividadesResueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActividadesResueltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_ListaTareas;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_ActividadesResueltas;
    // End of variables declaration//GEN-END:variables
}
