/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.awt.AWTUtilities;
import java.awt.Color;

/**
 *
 * @author andre
 */
public class CrearActividad extends javax.swing.JFrame {

    /**
     * Creates new form CrearActividad
     */
    public CrearActividad() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        
        jPanelTipoPreguntas.setBackground(new Color(254, 227, 198, 200));
        jPanel2.setBackground(new Color(254, 227, 198, 200));
        
        jButtonExaminarPre.setVisible(false);
        jLabelNombreArchivoPre.setVisible(false);
        jTextAreaRespuesta.setVisible(false);
        jScrollPaneRespuesta.setVisible(false);
        jLabelPreguntaA.setVisible(false);
        jLabelPreguntaB.setVisible(false);
        jLabelPreguntaC.setVisible(false);
        jLabelPreguntaD.setVisible(false);
        jTextFieldRespuesta1.setVisible(false);
        jTextFieldRespuesta2.setVisible(false);
        jTextFieldRespuesta3.setVisible(false);
        jTextFieldRespuesta4.setVisible(false);
        
        jButtonSiguientePre.setOpaque(false);
        jButtonSiguientePre.setContentAreaFilled(false);
        jButtonSiguientePre.setBorderPainted(false);
        
        jButtonAñadirTipoPre.setOpaque(false);
        jButtonAñadirTipoPre.setContentAreaFilled(false);
        jButtonAñadirTipoPre.setBorderPainted(false);
        
        jButtonGuardarTarea.setOpaque(false);
        jButtonGuardarTarea.setContentAreaFilled(false);
        jButtonGuardarTarea.setBorderPainted(false);
        
        jButtonVolver.setOpaque(false);
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.setBorderPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTipoPreguntas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipoPreguntas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPregunta = new javax.swing.JTextArea();
        jLabelNumPregunta = new javax.swing.JLabel();
        jLabelPreguntaA = new javax.swing.JLabel();
        jLabelPreguntaB = new javax.swing.JLabel();
        jLabelPreguntaC = new javax.swing.JLabel();
        jLabelPreguntaD = new javax.swing.JLabel();
        jTextFieldRespuesta1 = new javax.swing.JTextField();
        jTextFieldRespuesta2 = new javax.swing.JTextField();
        jTextFieldRespuesta3 = new javax.swing.JTextField();
        jTextFieldRespuesta4 = new javax.swing.JTextField();
        jButtonExaminarPre = new javax.swing.JButton();
        jLabelNombreArchivoPre = new javax.swing.JLabel();
        jScrollPaneRespuesta = new javax.swing.JScrollPane();
        jTextAreaRespuesta = new javax.swing.JTextArea();
        jButtonVolver = new javax.swing.JButton();
        jButtonExaminarGeneral = new javax.swing.JButton();
        jLabelNombreArchivoGeneral = new javax.swing.JLabel();
        jButtonGuardarTarea = new javax.swing.JButton();
        jButtonSiguientePre = new javax.swing.JButton();
        jButtonAñadirTipoPre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTipoPreguntas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipos de preguntas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        jPanelTipoPreguntas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione un tipo de pregunta:");
        jPanelTipoPreguntas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 23));

        jComboBoxTipoPreguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Icfes", "Abierta", "Completar" }));
        jPanelTipoPreguntas.add(jComboBoxTipoPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 110, -1));

        getContentPane().add(jPanelTipoPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 370, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preguntas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaPregunta.setColumns(20);
        jTextAreaPregunta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPregunta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 34, 467, 53));

        jLabelNumPregunta.setText("No.");
        jPanel2.add(jLabelNumPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 34, 25, 31));

        jLabelPreguntaA.setText("a)");
        jPanel2.add(jLabelPreguntaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 101, -1, -1));

        jLabelPreguntaB.setText("b)");
        jPanel2.add(jLabelPreguntaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 132, -1, -1));

        jLabelPreguntaC.setText("c)");
        jPanel2.add(jLabelPreguntaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 163, -1, -1));

        jLabelPreguntaD.setText("d)");
        jPanel2.add(jLabelPreguntaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 194, -1, -1));

        jTextFieldRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuesta1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 98, 447, -1));
        jPanel2.add(jTextFieldRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 129, 447, -1));
        jPanel2.add(jTextFieldRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 160, 447, -1));
        jPanel2.add(jTextFieldRespuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 191, 447, -1));

        jButtonExaminarPre.setText("Examinar");
        jPanel2.add(jButtonExaminarPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 229, 101, -1));

        jLabelNombreArchivoPre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelNombreArchivoPre.setText("Nombre de archivo cargado");
        jPanel2.add(jLabelNombreArchivoPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 288, 20));

        jScrollPaneRespuesta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respuesta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jTextAreaRespuesta.setColumns(20);
        jTextAreaRespuesta.setRows(5);
        jScrollPaneRespuesta.setViewportView(jTextAreaRespuesta);

        jPanel2.add(jScrollPaneRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 480, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 530, 280));

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.png"))); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 70, 50));

        jButtonExaminarGeneral.setText("Examinar");
        jButtonExaminarGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExaminarGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExaminarGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, -1));

        jLabelNombreArchivoGeneral.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelNombreArchivoGeneral.setText("Nombre de archivo de lectura general");
        getContentPane().add(jLabelNombreArchivoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 290, 20));

        jButtonGuardarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTarea.png"))); // NOI18N
        getContentPane().add(jButtonGuardarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 70, 50));

        jButtonSiguientePre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.png"))); // NOI18N
        getContentPane().add(jButtonSiguientePre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 70, 50));

        jButtonAñadirTipoPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarTarea.png"))); // NOI18N
        jButtonAñadirTipoPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirTipoPreActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAñadirTipoPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 50, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBordeCT2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespuesta1ActionPerformed

    private void jButtonAñadirTipoPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirTipoPreActionPerformed
        
        if (jComboBoxTipoPreguntas.getSelectedItem() == "Icfes") {
            jTextAreaRespuesta.setVisible(false);
            jScrollPaneRespuesta.setVisible(false);
            
            jLabelPreguntaA.setVisible(true);
            jLabelPreguntaB.setVisible(true);
            jLabelPreguntaC.setVisible(true);
            jLabelPreguntaD.setVisible(true);
            
            jTextFieldRespuesta1.setVisible(true);
            jTextFieldRespuesta2.setVisible(true);
            jTextFieldRespuesta3.setVisible(true);
            jTextFieldRespuesta4.setVisible(true);
            
            jButtonExaminarPre.setVisible(true);
            jLabelNombreArchivoPre.setVisible(true);
            
        } else if (jComboBoxTipoPreguntas.getSelectedItem() == "Abierta") {
            
            jTextAreaRespuesta.setVisible(true);
            jScrollPaneRespuesta.setVisible(true);
            
            jLabelPreguntaA.setVisible(false);
            jLabelPreguntaB.setVisible(false);
            jLabelPreguntaC.setVisible(false);
            jLabelPreguntaD.setVisible(false);
            
            jTextFieldRespuesta1.setVisible(false);
            jTextFieldRespuesta2.setVisible(false);
            jTextFieldRespuesta3.setVisible(false);
            jTextFieldRespuesta4.setVisible(false);
            
            jButtonExaminarPre.setVisible(true);
            jLabelNombreArchivoPre.setVisible(true);
            
        } else if (jComboBoxTipoPreguntas.getSelectedItem() == "Completar") {
            
        }
        

    }//GEN-LAST:event_jButtonAñadirTipoPreActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonExaminarGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExaminarGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExaminarGeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirTipoPre;
    private javax.swing.JButton jButtonExaminarGeneral;
    private javax.swing.JButton jButtonExaminarPre;
    private javax.swing.JButton jButtonGuardarTarea;
    private javax.swing.JButton jButtonSiguientePre;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxTipoPreguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNombreArchivoGeneral;
    private javax.swing.JLabel jLabelNombreArchivoPre;
    private javax.swing.JLabel jLabelNumPregunta;
    private javax.swing.JLabel jLabelPreguntaA;
    private javax.swing.JLabel jLabelPreguntaB;
    private javax.swing.JLabel jLabelPreguntaC;
    private javax.swing.JLabel jLabelPreguntaD;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTipoPreguntas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneRespuesta;
    private javax.swing.JTextArea jTextAreaPregunta;
    private javax.swing.JTextArea jTextAreaRespuesta;
    private javax.swing.JTextField jTextFieldRespuesta1;
    private javax.swing.JTextField jTextFieldRespuesta2;
    private javax.swing.JTextField jTextFieldRespuesta3;
    private javax.swing.JTextField jTextFieldRespuesta4;
    // End of variables declaration//GEN-END:variables
}
