/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.Principal.jLabelBienvenidos;
import static GUI.Principal.jLabelDocente;
import static GUI.Principal.jLabelEstudiante;
import static GUI.Principal.jbDocente;
import static GUI.Principal.jbEstudiante;
import Logica.ConexionMySql;
import Logica.MetodosBD;
import Logica.MetodosLogica;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author Andres Mancilla Oliver
 * @author Andres Felipe Otalvaro
 *
 * Interfaz para la ventana Estudiante.
 */
public class Estudiante extends javax.swing.JInternalFrame {

    MetodosBD metodobd = new MetodosBD(this);
    int con3 = 2;

    private static ListaEstudiantes listaEstudiantes;

    public Estudiante(ListaEstudiantes listaEstudiantes) {
        this.listaEstudiantes = listaEstudiantes;
    }

    /**
     * Creates new form Estudiante
     */
    public Estudiante(String grado) {

        initComponents();
        metodobd.cargarActividadesEstudiante();
        txtRespuesta.setVisible(false);
        rbtnRespuesta1.setVisible(false);
        rbtnRespuesta2.setVisible(false);
        rbtnRespuesta3.setVisible(false);
        rbtnRespuesta4.setVisible(false);
        lblActividad.setVisible(false);
        lblNumeroPregunta.setVisible(false);
        txtAreaPregunta.setVisible(false);
        jScrollPane2.setVisible(false);
        btnSiguiente.setVisible(false);

        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Actividades = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombreEstudiante = new javax.swing.JLabel();
        jLabel_texGra = new javax.swing.JLabel();
        jButtonSalirEstudiante = new javax.swing.JButton();
        jButtonVolverEstu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Grado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblActividad = new javax.swing.JLabel();
        rbtnRespuesta1 = new javax.swing.JRadioButton();
        rbtnRespuesta2 = new javax.swing.JRadioButton();
        rbtnRespuesta3 = new javax.swing.JRadioButton();
        rbtnRespuesta4 = new javax.swing.JRadioButton();
        lblNumeroPregunta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaPregunta = new javax.swing.JTextArea();
        txtRespuesta = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximizable(true);
        setTitle("Estudiantes");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(916, 603));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lista de actividades");

        jList_Actividades.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jList_Actividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_ActividadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Actividades);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreEstudiante.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jPanel2.add(jLabelNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 310, 30));

        jLabel_texGra.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel_texGra.setText("Grado ");
        jPanel2.add(jLabel_texGra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 30));

        jButtonSalirEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        jButtonSalirEstudiante.setContentAreaFilled(false);
        jButtonSalirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEstudianteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalirEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 62, 45));

        jButtonVolverEstu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver2.png"))); // NOI18N
        jButtonVolverEstu.setContentAreaFilled(false);
        jButtonVolverEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverEstuActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolverEstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 18, 57, 45));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barraEstudiantes.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 170, 90));

        jLabel_Grado.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jPanel2.add(jLabel_Grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        lblActividad.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jPanel3.add(lblActividad);
        lblActividad.setBounds(120, 20, 410, 40);

        rbtnGrupo.add(rbtnRespuesta1);
        rbtnRespuesta1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtnRespuesta1.setText("\"\"");
        rbtnRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRespuesta1ActionPerformed(evt);
            }
        });
        jPanel3.add(rbtnRespuesta1);
        rbtnRespuesta1.setBounds(102, 208, 290, 37);

        rbtnGrupo.add(rbtnRespuesta2);
        rbtnRespuesta2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtnRespuesta2.setText("\"\"");
        jPanel3.add(rbtnRespuesta2);
        rbtnRespuesta2.setBounds(100, 240, 290, 37);

        rbtnGrupo.add(rbtnRespuesta3);
        rbtnRespuesta3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtnRespuesta3.setText("\"\"");
        jPanel3.add(rbtnRespuesta3);
        rbtnRespuesta3.setBounds(100, 280, 290, 37);

        rbtnGrupo.add(rbtnRespuesta4);
        rbtnRespuesta4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtnRespuesta4.setText("\"\"");
        jPanel3.add(rbtnRespuesta4);
        rbtnRespuesta4.setBounds(100, 310, 290, 37);

        lblNumeroPregunta.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNumeroPregunta.setText("1");
        jPanel3.add(lblNumeroPregunta);
        lblNumeroPregunta.setBounds(39, 87, 40, 40);

        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAreaPregunta.setEditable(false);
        txtAreaPregunta.setColumns(20);
        txtAreaPregunta.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        txtAreaPregunta.setRows(5);
        txtAreaPregunta.setBorder(null);
        jScrollPane2.setViewportView(txtAreaPregunta);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(100, 90, 456, 90);

        txtRespuesta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(txtRespuesta);
        txtRespuesta.setBounds(100, 210, 460, 90);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnSiguiente);
        btnSiguiente.setBounds(240, 380, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRespuesta1ActionPerformed

    private void jButtonSalirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEstudianteActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirEstudianteActionPerformed

    private void jButtonVolverEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverEstuActionPerformed
        dispose();
        Principal.VentaPrincipal.show();
        jbDocente.setVisible(true);
        jbEstudiante.setVisible(true);
        jLabelDocente.setVisible(true);
        jLabelEstudiante.setVisible(true);
        jLabelBienvenidos.setVisible(true);
    }//GEN-LAST:event_jButtonVolverEstuActionPerformed

    private void jList_ActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_ActividadesMouseClicked
        metodobd.consultaActividad();
        jList_Actividades.enable(false);


    }//GEN-LAST:event_jList_ActividadesMouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:

        if (!txtRespuesta.isVisible()) {

            if (rbtnRespuesta1.isSelected()) {
                metodobd.agregarRespuesta("Icfes", rbtnRespuesta1.getText().toString());
            }
            if (rbtnRespuesta2.isSelected()) {
                metodobd.agregarRespuesta("Icfes", rbtnRespuesta2.getText().toString());
            }
            if (rbtnRespuesta3.isSelected()) {
                metodobd.agregarRespuesta("Icfes", rbtnRespuesta3.getText().toString());
            }
            if (rbtnRespuesta4.isSelected()) {
                metodobd.agregarRespuesta("Icfes", rbtnRespuesta4.getText().toString());
            }

        } else {
            metodobd.agregarRespuesta("Abierta", txtRespuesta.getText());

        }
        lblNumeroPregunta.setText("" + con3);
        con3++;
        metodobd.siguientePregunta();
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButtonSalirEstudiante;
    private javax.swing.JButton jButtonVolverEstu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabelNombreEstudiante;
    public static javax.swing.JLabel jLabel_Grado;
    public static javax.swing.JLabel jLabel_texGra;
    public static javax.swing.JList<String> jList_Actividades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblActividad;
    public javax.swing.JLabel lblNumeroPregunta;
    private javax.swing.ButtonGroup rbtnGrupo;
    public javax.swing.JRadioButton rbtnRespuesta1;
    public javax.swing.JRadioButton rbtnRespuesta2;
    public javax.swing.JRadioButton rbtnRespuesta3;
    public javax.swing.JRadioButton rbtnRespuesta4;
    public javax.swing.JTextArea txtAreaPregunta;
    public javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
