/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.Principal.jbEstudiante;
import Logica.MetodosLogin;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author andre
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldUsuario.setBorder(new EmptyBorder(0, 5, 0, 2));
        jPasswordField1.setBorder(new EmptyBorder(0, 5, 0, 2));

        jB_Registro.setOpaque(false);
        jB_Registro.setContentAreaFilled(false);
        jB_Registro.setBorderPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_CancelarLogin = new javax.swing.JButton();
        jB_AceptarLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jB_Registro = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_CancelarLogin.setText("Cancelar");
        jB_CancelarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CancelarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jB_CancelarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jB_AceptarLogin.setText("Aceptar");
        jB_AceptarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AceptarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jB_AceptarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/001-bloquear-1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 40, 40));

        jLabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_login_orange.png"))); // NOI18N
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, 50));

        jTextFieldUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jTextFieldUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 180, 30));

        jLabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profeLogin.png"))); // NOI18N
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 110, 110));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 30));

        jB_Registro.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jB_Registro.setForeground(new java.awt.Color(51, 102, 255));
        jB_Registro.setText("Registrarse");
        jB_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 120, 20));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogin.jpg"))); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 288));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_CancelarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CancelarLoginActionPerformed
        this.dispose();
        Principal.jbDocente.setVisible(true);
        Principal.jbEstudiante.setVisible(true);
        Principal.jLabelBienvenidos.setVisible(true);
        Principal.jLabelDocente.setVisible(true);
        Principal.jLabelEstudiante.setVisible(true);
    }//GEN-LAST:event_jB_CancelarLoginActionPerformed

    MetodosLogin metodos = new MetodosLogin();
    private void jB_AceptarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AceptarLoginActionPerformed

        if (metodos.validar_ingreso() == 1) {
            this.dispose();

            try {

                Docente docente = new Docente();
                Principal.VentaPrincipal.add(docente);
                Principal.VentaPrincipal.moveToFront(docente);
                docente.setSize(Principal.VentaPrincipal.getWidth(), Principal.VentaPrincipal.getHeight());
                docente.setLocation(0, 0);
                docente.show();

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            System.out.println(metodos.validar_ingreso());
            System.out.println();
            JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos\n"
                    + "Verifique sus datos y vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_AceptarLoginActionPerformed

    private void jRPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRPasswordField1ActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed

    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jB_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RegistroActionPerformed
        this.dispose();
        RegistroDocente registro = new RegistroDocente();
        registro.show();
    }//GEN-LAST:event_jB_RegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AceptarLogin;
    private javax.swing.JButton jB_CancelarLogin;
    private javax.swing.JButton jB_Registro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelUser;
    public static javax.swing.JPasswordField jPasswordField1;
    public static javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    private static class RoundedBorder implements Border {

        private int radius;

        RoundedBorder(int radius) {
            this.radius = radius;
        }

        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
        }

        public boolean isBorderOpaque() {
            return true;
        }

        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }
    }
}
