/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logica.ConexionMySql;
import java.awt.Image;
import java.awt.Graphics;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);

        jButtonExit.setOpaque(false);
        jButtonExit.setContentAreaFilled(false);
        jButtonExit.setBorderPainted(false);

        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/imgLogo.png")).getImage());
    }

    public void transparenciaBoton() {

        jbEstudiante.setOpaque(false);
        jbEstudiante.setContentAreaFilled(false);
        jbEstudiante.setBorderPainted(false);

        jbDocente.setOpaque(false);
        jbDocente.setContentAreaFilled(false);
        jbDocente.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"));
        Image image = icon.getImage();
        VentaPrincipal = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);}
        }
        ;
        jbEstudiante = new javax.swing.JButton();
        jbDocente = new javax.swing.JButton();
        jLabelBienvenidos = new javax.swing.JLabel();
        jLabelEstudiante = new javax.swing.JLabel();
        jLabelDocente = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RafaLee");
        setUndecorated(true);

        VentaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        VentaPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        jbEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estudiantes.png"))); // NOI18N
        jbEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstudianteActionPerformed(evt);
            }
        });

        jbDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/docente.png"))); // NOI18N
        jbDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDocenteActionPerformed(evt);
            }
        });

        jLabelBienvenidos.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jLabelBienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bienvenidos.png"))); // NOI18N

        jLabelEstudiante.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estudiante.png"))); // NOI18N

        jLabelDocente.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Docente_1.png"))); // NOI18N

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButton1.setText("Probar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        VentaPrincipal.setLayer(jbEstudiante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VentaPrincipal.setLayer(jbDocente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VentaPrincipal.setLayer(jLabelBienvenidos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VentaPrincipal.setLayer(jLabelEstudiante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VentaPrincipal.setLayer(jLabelDocente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VentaPrincipal.setLayer(jButtonExit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VentaPrincipal.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VentaPrincipalLayout = new javax.swing.GroupLayout(VentaPrincipal);
        VentaPrincipal.setLayout(VentaPrincipalLayout);
        VentaPrincipalLayout.setHorizontalGroup(
            VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentaPrincipalLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstudiante))
                .addGap(75, 75, 75)
                .addGroup(VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDocente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDocente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentaPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelBienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentaPrincipalLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonExit)
                        .addContainerGap())))
        );
        VentaPrincipalLayout.setVerticalGroup(
            VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabelBienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentaPrincipalLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jbDocente))
                    .addComponent(jbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(VentaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(VentaPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstudianteActionPerformed

        ListaEstudiantes lista = new ListaEstudiantes();
        lista.show();

        jbDocente.setVisible(false);
        jbEstudiante.setVisible(false);
        jLabelDocente.setVisible(false);
        jLabelEstudiante.setVisible(false);
        jLabelBienvenidos.setVisible(false);


    }//GEN-LAST:event_jbEstudianteActionPerformed

    private void jbDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDocenteActionPerformed

        Login login = new Login();
        login.show();

        jbDocente.setVisible(false);
        jbEstudiante.setVisible(false);
        jLabelBienvenidos.setVisible(false);
        jLabelDocente.setVisible(false);
        jLabelEstudiante.setVisible(false);

    }//GEN-LAST:event_jbDocenteActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ConexionMySql mysql = new ConexionMySql();
        java.sql.Connection cn = mysql.Conectar();
        if (!cn.equals(null)) {
            JOptionPane.showMessageDialog(null, "Conectado");
            try {
                cn.close();
            } catch (SQLException ex) {
                System.out.println("Error al desconectar " + ex);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    Thread.sleep(2000);
                } catch (Exception e) {

                }
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane VentaPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExit;
    public static javax.swing.JLabel jLabelBienvenidos;
    public static javax.swing.JLabel jLabelDocente;
    public static javax.swing.JLabel jLabelEstudiante;
    public static javax.swing.JButton jbDocente;
    public static javax.swing.JButton jbEstudiante;
    // End of variables declaration//GEN-END:variables
}
