/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logica.ConexionMySql;
import Logica.Pool;
import java.awt.Color;
import java.awt.Image;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);

        jButtonExit.setOpaque(false);
        jButtonExit.setContentAreaFilled(false);
        jButtonExit.setBorderPainted(false);

        jbEstudiante.setOpaque(false);
        jbEstudiante.setContentAreaFilled(false);
        jbEstudiante.setBorderPainted(false);

        jbDocente.setOpaque(false);
        jbDocente.setContentAreaFilled(false);
        jbDocente.setBorderPainted(false);

        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/imgLogo.png")).getImage());

        ConexionMySql c = new ConexionMySql();
        if (c.Conectar() != null) {
            jLabel_Conexion.setText("Conectado");
            jLabel_Conexion.setForeground(Color.GREEN);
        } else {
            jLabel_Conexion.setText("Desconectado");
            jLabel_Conexion.setForeground(Color.RED);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"));
        Image image = icon.getImage();
        VentaPrincipal = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);}
        }
        ;
        jbEstudiante = new javax.swing.JButton();
        jbDocente = new javax.swing.JButton();
        jLabelBienvenidos = new javax.swing.JLabel();
        jLabelEstudiante = new javax.swing.JLabel();
        jLabelDocente = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel_Conexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RafaLee");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VentaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        VentaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        VentaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estudiantes.png"))); // NOI18N
        jbEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstudianteActionPerformed(evt);
            }
        });
        VentaPrincipal.add(jbEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 154, 257, 245));

        jbDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/docente.png"))); // NOI18N
        jbDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDocenteActionPerformed(evt);
            }
        });
        VentaPrincipal.add(jbDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 156, -1, -1));

        jLabelBienvenidos.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jLabelBienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bienvenidos.png"))); // NOI18N
        VentaPrincipal.add(jLabelBienvenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 70, 424, 73));

        jLabelEstudiante.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estudiante.png"))); // NOI18N
        VentaPrincipal.add(jLabelEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 420, -1, 35));

        jLabelDocente.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Docente_1.png"))); // NOI18N
        VentaPrincipal.add(jLabelDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 410, -1, 34));

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        VentaPrincipal.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 11, -1, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        VentaPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 29, -1, -1));
        VentaPrincipal.add(jLabel_Conexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 120, 20));

        getContentPane().add(VentaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstudianteActionPerformed

        ListaEstudiantes lista = new ListaEstudiantes();
        lista.show();

        jbDocente.setVisible(false);
        jbEstudiante.setVisible(false);
        jLabelDocente.setVisible(false);
        jLabelEstudiante.setVisible(false);
        jLabelBienvenidos.setVisible(false);


    }//GEN-LAST:event_jbEstudianteActionPerformed

    private void jbDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDocenteActionPerformed

        Login login = new Login();
        login.show();

        jbDocente.setVisible(false);
        jbEstudiante.setVisible(false);
        jLabelBienvenidos.setVisible(false);
        jLabelDocente.setVisible(false);
        jLabelEstudiante.setVisible(false);

    }//GEN-LAST:event_jbDocenteActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Pool metodospool = new Pool();
        java.sql.Connection cn = null;
        try {
            cn = metodospool.dataSource.getConnection();
            if (cn != null) {
                JOptionPane.showMessageDialog(null, "Conectado");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            try {
                cn.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    Thread.sleep(2000);
                } catch (Exception e) {

                }
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane VentaPrincipal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonExit;
    public static javax.swing.JLabel jLabelBienvenidos;
    public static javax.swing.JLabel jLabelDocente;
    public static javax.swing.JLabel jLabelEstudiante;
    private javax.swing.JLabel jLabel_Conexion;
    public static javax.swing.JButton jbDocente;
    public static javax.swing.JButton jbEstudiante;
    // End of variables declaration//GEN-END:variables
}
